import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import { AuthProvider } from "@/context/AuthContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="h-screen flex">
        <AuthProvider>
          <Sidebar></Sidebar>
          <main className="flex-1 p-6 overflow-y-auto bg-gray-50">
            {children}
          </main>
        </AuthProvider>
      </body>
    </html>
  );
}
