import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import { AuthProvider } from "@/context/AuthContext";
import Script from "next/script";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Script
          type="text/javascript"
          src={`https://openapi.map.naver.com/openapi/v3/maps.js?ncpClientId=${process.env.NEXT_PUBLIC_NAVER_CLIENT_ID}&submodules=geocoder`}
        ></Script>
      </head>
      <body className="h-screen flex">
        <AuthProvider>
          <Sidebar></Sidebar>
          <main className="flex-1 p-6 overflow-y-auto bg-gray-50">
            {children}
          </main>
        </AuthProvider>
      </body>
    </html>
  );
}
